### ISSUE TITLE
Building on Mac

### ISSUE THREAD

**Issue by VReelTeam** [eamonwoortman/RestSharp.Unity#5]
As a Mac user with the same problem that the RestSharp.dll does not seem to work in Unity (in particular for Android), how do I build your project?

It appears like it only builds on Windows, and I don't have a Windows machine handy =(

------------------------------------------------------------------

The actual problem I'm having is that the "RestSharp.105.2.3" "net35" version seems to work fine in the Unity Editor but when I build the apk for Android (in a project built for Android API Level 19 "Kit Kat") I get the below error - do you believe building your forked version of RestSharp should solve this..?

*ArgumentOutOfRangeException: Argument is out of range.
Parameter name: options
  at System.Text.RegularExpressions.Regex.validate_options (RegexOptions options) [0x0003a] in /Users/builduser/buildslave/mono/build/mcs/class/System/System.Text.RegularExpressions/Regex.cs:248 
   at System.Text.RegularExpressions.Regex..ctor (System.String pattern, RegexOptions options) [0x00017] in /Users/builduser/buildslave/mono/build/mcs/class/System/System.Text.RegularExpressions/Regex.cs:214 
   at RestSharp.RestClient..ctor () [0x00000] in <filename unknown>:0 
   at RestSharp.RestClient..ctor (System.String baseUrl) [0x00000] in <filename unknown>:0*

**Comment by eamonwoortman** [comment]
Hi @VReelTeam,

Your Android issue perfectly describes the incompatibility issue this fork fixes. 

Due to lack of time I have neglected this repo a bit. That's the reason why it doesn't have a proper README addition or releases. 
However, I have taken the liberty of quickly building the latest master branch. I don't have time to test it, but maybe you could. https://github.com/eamonwoortman/RestSharp.Unity/releases/tag/105.2.3-unity-aad4d59

A while back I created a small Unity project which runs a few simple tests. 
You can clone it from https://github.com/eamonwoortman/RestSharp.Unity.Tester. In that project you will also find pre-build binaries of the library, but I don't recall it's version.
 
Again, at the moment I don't have time to maintain this repository, so I hope this will suffice for now.

Cheers,

Eamon

**Comment by VReelTeam** [comment]
Hi @eamonwoortman!

I've just grabbed the "x86_64" version of RestSharp.dll and it appears to have worked for my use-case!

Thank you so much for the swift reply!

I'll end up testing the library with anger naturally during this week - if I find that in fact there's a problem with it then I'll update this thread!

Thanks!
